# Generated by Django 5.2.5 on 2025-08-21 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'md', 'rtf', 'doc', 'docx', 'odt', 'pdf', 'html', 'htm', 'zip'])]),
        ),
    ]
