# Generated by Django 5.2.5 on 2025-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_textdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
