# Generated by Django 5.2.5 on 2025-08-24 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_textdocument_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='file',
            field=models.FileField(upload_to='user_directory_path', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'doc', 'docx', 'rtf', 'odt', 'tex', 'wps', 'ppt', 'pptx', 'xls', 'xlsx'])]),
        ),
    ]
